modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "enchantinnovation"
version = "${version}"
displayName = "EnchantInnovation"
authors = "yyz729"
description = '''
https://modrinth.com/mod/enchant-innovation
https://github.com/yyz729/EnchantInnovation
'''
#logoFile = ""

[[dependencies.enchantinnovation]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantinnovation]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "enchantinnovation.mixins.json"
